openapi: 3.0.2
info:
    title: Activity Tracking API
    version: 1.0.0
    description: Activity Tracking API for the Globex Retail site.
    license:
        name: MIT License
        url: 'https://opensource.org/licenses/MIT'
paths:
    /track:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/activity-tracking-payload'
                        examples:
                            activity-tracking-example:
                                value:
                                    idSite: globex-retail
                                    activity:
                                        userId: 7672a49e-9afc-498f-91bc-98f881179f2c
                                        url: 'https://globex-retail.com/product/12345/details'
                                        rand: ba6eb330-4f7f-11eb-a2fb-67c34e9ac07c
                                        type: like
                                    userInfo:
                                        visitsCount: 1
                                        prevVisitTs: 1647249258
                                        firstVisitTs: 1647249258
                                        campaign: abc123
                                        localTime: '2022-03-14T09:26:04+00:00'
                                        newVisit: 1
                                    actionInfo:
                                        productId: a12345
                                        category: cat123456
                                        search: waterbottle
                                        searchCat: swag
                required: true
            responses:
                '200':
                    description: OK
                '400':
                    description: Bad Request
                '403':
                    description: Forbidden
                '500':
                    description: Internal Server Error
            security:
                -
                    activity-tracker-api: []
components:
    schemas:
        activity-tracking-payload:
            title: Root Type for activity-tracking-payload
            description: Payload sent with POST requests to activity tracking API
            required:
                - activity
                - idSite
                - userInfo
            type: object
            properties:
                idSite:
                    type: string
                activity:
                    $ref: '#/components/schemas/activity'
                    properties:
                        userId:
                            type: string
                        url:
                            type: string
                        rand:
                            type: string
                        type:
                            type: string
                userInfo:
                    $ref: '#/components/schemas/user-info'
                    properties:
                        visitsCount:
                            format: int32
                            type: integer
                        prevVisitTs:
                            format: int32
                            type: integer
                        firstVisitTs:
                            format: int32
                            type: integer
                        campaign:
                            type: string
                        localTime:
                            format: date-time
                            type: string
                        newVisit:
                            format: int32
                            type: integer
                actionInfo:
                    $ref: '#/components/schemas/action-info'
                    properties:
                        productId:
                            type: string
                        category:
                            type: string
                        search:
                            type: string
                        searchCat:
                            type: string
            example:
                idSite: globex-retail
                activity:
                    userId: 7672a49e-9afc-498f-91bc-98f881179f2c
                    url: 'https://globex-retail.com/product/12345/details'
                    rand: ba6eb330-4f7f-11eb-a2fb-67c34e9ac07c
                    type: like
                userInfo:
                    visitsCount: 1
                    prevVisitTs: 1647249258
                    firstVisitTs: 1647249258
                    campaign: abc123
                    localTime: '2022-03-14T09:26:04+00:00'
                    newVisit: 1
                actionInfo:
                    productId: a12345
                    category: cat123456
                    search: waterbottle
                    searchCat: swag
        activity:
            title: Root Type for activity
            description: ''
            required:
                - rand
                - type
                - url
                - userId
            type: object
            properties:
                userId:
                    type: string
                url:
                    type: string
                rand:
                    type: string
                type:
                    type: string
            example:
                userId: 7672a49e-9afc-498f-91bc-98f881179f2c
                url: 'https://globex-retail.com/product/12345/details'
                rand: ba6eb330-4f7f-11eb-a2fb-67c34e9ac07c
                type: like
        user-info:
            title: Root Type for user-info
            description: ''
            required:
                - localTime
            type: object
            properties:
                visitsCount:
                    type: integer
                prevVisitTs:
                    type: integer
                firstVisitTs:
                    type: integer
                campaign:
                    type: string
                localTime:
                    format: date-time
                    type: string
                newVisit:
                    type: integer
            example:
                visitsCount: 1
                prevVisitTs: 1647249258
                firstVisitTs: 1647249258
                campaign: abc123
                localTime: '2022-03-14T09:26:04+00:00'
                newVisit: 1
        action-info:
            title: Root Type for action-info
            description: ''
            type: object
            properties:
                search:
                    type: string
                category:
                    type: string
                searchCat:
                    type: string
                productId:
                    type: string
            example:
                productId: a12345
                category: cat123456
                search: waterbottle
                searchCat: swag
    securitySchemes:
        activity-tracker-api:
            type: apiKey
            name: api_key
            in: query
security:
    -
        activity-tracker-api: []
tags:
    -
        name: retail
        description: ''
    -
        name: activity-tracking
        description: ''
